# Generated by Django 5.2.8 on 2025-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("area", models.PositiveIntegerField()),
                ("rooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("age", models.PositiveIntegerField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("villa", "Villa"),
                            ("apartment", "Apartment"),
                            ("land", "Land"),
                        ],
                        max_length=50,
                    ),
                ),
                ("main_image", models.ImageField(upload_to="properties/main/")),
                ("title_deed", models.FileField(upload_to="properties/documents/")),
                (
                    "ownership_proof",
                    models.FileField(upload_to="properties/documents/"),
                ),
                (
                    "building_license",
                    models.FileField(
                        blank=True, null=True, upload_to="properties/documents/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/gallery/")),
            ],
        ),
    ]
