# Generated by Django 5.2.8 on 2025-12-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                choices=[
                    ("Riyadh", "Riyadh"),
                    ("Jeddah", "Jeddah"),
                    ("Dammam", "Dammam"),
                    ("Mecca", "Mecca"),
                    ("Medina", "Medina"),
                    ("Khobar", "Khobar"),
                    ("Tabuk", "Tabuk"),
                    ("Abha", "Abha"),
                    ("Hail", "Hail"),
                    ("Buraidah", "Buraidah"),
                    ("Al Bahah", "Al Bahah"),
                    ("Najran", "Najran"),
                    ("Jazan", "Jazan"),
                    ("Arar", "Arar"),
                    ("Sakaka", "Sakaka"),
                ],
                max_length=100,
            ),
        ),
    ]
