# Generated by Django 5.2.8 on 2025-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_property_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                choices=[
                    ("Riyadh", "Riyadh"),
                    ("Jeddah", "Jeddah"),
                    ("Dammam", "Dammam"),
                    ("Khobar", "Khobar"),
                    ("Makkah", "Makkah"),
                    ("Madina", "Madina"),
                    ("Abha", "Abha"),
                    ("Tabuk", "Tabuk"),
                    ("Qassim", "Qassim"),
                    ("Hail", "Hail"),
                    ("Najran", "Najran"),
                    ("Jazan", "Jazan"),
                    ("Buraidah", "Buraidah"),
                    ("Al-Ahsa", "Al-Ahsa"),
                    ("Taif", "Taif"),
                    ("Baha", "Baha"),
                ],
                max_length=100,
            ),
        ),
    ]
