# Generated by Django 5.2.8 on 2025-12-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deed_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
