# Generated by Django 5.2.8 on 2025-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
